// Generated by CoffeeScript 1.10.0
(function() {
  var CronJob, Model, Promise, elastic, job;

  CronJob = require('cron').CronJob;

  Model = require('../models/model.js').Model;

  elastic = require('./elastic');

  Promise = require('bluebird');

  job = new CronJob('0 */1 * * * *', (function() {
    var comment, comments, creative, creatives, tag, tags, user, users;
    tag = elastic.initialize('tag');
    user = elastic.initialize('user');
    creative = elastic.initialize('creative');
    comment = elastic.initialize('comment');
    tags = Model.Tag.findAll();
    users = Model.User.findAll();
    comments = Model.Comment.findAll();
    creatives = Model.Creative.findAll();
    Promise.all([tags, users, comments, creatives, tag, user, creative, comment]).spread(function(tags, users, comments, creatives) {
      var commentsPromises, creativesPromises, tagsPromises, usersPromises;
      tagsPromises = tags.map(function(tag) {
        return elastic.add('tag', tag.name, tag.name);
      });
      usersPromises = users.map(function(user) {
        return elastic.add('user', user.firstName + ' ' + user.lastName + ' ' + user.about, user.authId);
      });
      commentsPromises = comments.map(function(comment) {
        return elastic.add('comment', comment.body, comment.body);
      });
      creativesPromises = creatives.map(function(creative) {
        return elastic.add('creative', creative.title + ' ' + creative.article, creative.title);
      });
      return Promise.all([tagsPromises, usersPromises, commentsPromises, creativesPromises]).then(function() {});
    });
  }), (function() {}), true);

}).call(this);

//# sourceMappingURL=cronJobForElastic.js.map
