// Generated by CoffeeScript 1.10.0
(function() {
  var add, deleteIndex, elasticClient, elasticsearch, getSuggestions, indexExists, initIndex, initMapping, initialize;

  elasticsearch = require('elasticsearch');

  elasticClient = new elasticsearch.Client;

  deleteIndex = function(indexName) {
    return elasticClient.indices["delete"]({
      index: indexName
    });
  };

  initIndex = function(indexName) {
    return elasticClient.indices.create({
      index: indexName
    });
  };

  indexExists = function(indexName) {
    return elasticClient.indices.exists({
      index: indexName
    });
  };

  initMapping = function(indexName) {
    return elasticClient.indices.putMapping({
      index: indexName,
      type: 'something',
      body: {
        properties: {
          title: {
            type: 'string'
          },
          suggest: {
            type: 'completion',
            analyzer: 'standard',
            search_analyzer: 'standard',
            payloads: true
          }
        }
      }
    });
  };

  initialize = function(indexName) {
    return indexExists(indexName).then(function(exists) {
      if (exists) {
        return deleteIndex(indexName);
      }
    }).then(function() {
      return initIndex(indexName);
    }).then(function() {
      return initMapping(indexName);
    });
  };

  add = function(indexName, title, post) {
    return elasticClient.index({
      index: indexName,
      type: 'something',
      body: {
        title: title,
        suggest: {
          input: title.split(' '),
          output: post
        }
      }
    });
  };

  getSuggestions = function(indexName, input) {
    return elasticClient.suggest({
      index: indexName,
      type: 'something',
      body: {
        docsuggest: {
          text: input,
          completion: {
            field: 'suggest',
            fuzzy: true
          }
        }
      }
    });
  };

  exports.deleteIndex = deleteIndex;

  exports.initIndex = initIndex;

  exports.indexExists = indexExists;

  exports.initMapping = initMapping;

  exports.initialize = initialize;

  exports.add = add;

  exports.getSuggestions = getSuggestions;

}).call(this);

//# sourceMappingURL=elastic.js.map
