// Generated by CoffeeScript 1.10.0
(function() {
  var ENV, getLogger, winston;

  winston = require('winston');

  ENV = process.env.NODE_ENV;

  getLogger = function(module) {
    var path;
    path = module.filename.split('/').slice(-2).join('/');
    return new winston.Logger({
      transports: [
        new winston.transports.Console({
          colorize: true,
          level: ENV === 'development' ? 'debug' : 'error',
          label: path
        })
      ]
    });
  };

  module.exports = getLogger;

}).call(this);

//# sourceMappingURL=log.js.map
