// Generated by CoffeeScript 1.10.0
(function() {
  var HttpError, http, path, util;

  path = require('path');

  util = require('util');

  http = require('http');

  HttpError = function(status, message) {
    Error.apply(this, arguments);
    Error.captureStackTrace(this, HttpError);
    this.status = status;
    this.message = message || http.STATUS_CODES[status] || 'Error';
  };

  util.inherits(HttpError, Error);

  HttpError.prototype.name = 'HttpError';

  exports.HttpError = HttpError;

}).call(this);

//# sourceMappingURL=index.js.map
