// Generated by CoffeeScript 1.10.0
(function() {
  var registrationRedirectPatn;

  registrationRedirectPatn = 'http://localhost:8000/app/#/';

  exports.post = function(req, res) {
    res.locals.user = null;
    req.session.user = null;
    res.sendStatus(200);
  };

}).call(this);

//# sourceMappingURL=logout.js.map
