// Generated by CoffeeScript 1.10.0
(function() {
  var Model, uuid;

  Model = require('../models/model.js').Model;

  uuid = require('uuid');

  exports.post = function(req, res, next) {
    var about, email, language, password, surname, theme, username;
    username = req.body.username;
    password = req.body.password;
    email = req.body.email;
    surname = req.body.surname;
    about = req.body.about;
    theme = req.body.theme;
    language = req.body.language;
    Model.User.findOne({
      where: {
        email: email
      }
    }).then(function(user) {
      if (user) {
        return null;
      }
      return Model.User.create({
        authId: uuid.v1(),
        theme: theme,
        language: language,
        firstName: username,
        lastName: surname,
        email: email,
        about: about,
        password: password
      });
    }).then(function(user) {
      if (user) {
        req.session.user = user.authId;
        res.send(user);
      } else {
        req.session.user = null;
        res.sendStatus(403);
      }
    });
  };

}).call(this);

//# sourceMappingURL=registry.js.map
