// Generated by CoffeeScript 1.10.0
(function() {
  var Model, registrationRedirectPath;

  registrationRedirectPath = 'http://localhost:8000/app/#/';

  Model = require('../models/model.js').Model;

  exports.log = function(req, res) {
    console.log(req.sessionID);
    return Model.Passport.create({
      user: req.user.dataValues.authId
    }).then(function() {
      return res.redirect(registrationRedirectPath);
    });
  };

}).call(this);

//# sourceMappingURL=social.js.map
