elasticsearch = require('elasticsearch')
elasticClient = new (elasticsearch.Client)

deleteIndex = (indexName) ->
  elasticClient.indices.delete index: indexName

initIndex = (indexName) ->
  elasticClient.indices.create index: indexName

indexExists = (indexName) ->
  elasticClient.indices.exists index: indexName

initMapping = (indexName) ->
  elasticClient.indices.putMapping
    index: indexName
    type: 'something'
    body: properties:
      title: type: 'string'
      suggest:
        type: 'completion'
        analyzer: 'standard'
        search_analyzer: 'standard'
        payloads: true

initialize = (indexName) ->
  indexExists(indexName).then((exists) ->
    if exists
      return deleteIndex(indexName)
    return
  ).then(->
    initIndex indexName
  ).then ->
    initMapping indexName

add = (indexName, title, post) ->
  elasticClient.index
    index: indexName
    type: 'something'
    body:
      title: title
      suggest:
        input: title.split(' ')
        output: post

getSuggestions = (indexName, input) ->
  elasticClient.suggest
    index: indexName
    type: 'something'
    body: docsuggest:
      text: input
      completion:
        field: 'suggest'
        fuzzy: true

exports.deleteIndex = deleteIndex
exports.initIndex = initIndex
exports.indexExists = indexExists
exports.initMapping = initMapping
exports.initialize = initialize
exports.add = add
exports.getSuggestions = getSuggestions

# ---
# generated by js2coffee 2.1.0