path = require('path')
util = require('util')
http = require('http')

HttpError = (status, message) ->
  Error.apply this, arguments
  Error.captureStackTrace this, HttpError
  @status = status
  @message = message or http.STATUS_CODES[status] or 'Error'
  return

util.inherits HttpError, Error
HttpError::name = 'HttpError'
exports.HttpError = HttpError

# ---
# generated by js2coffee 2.1.0